import { PhonemeContent } from '../types';

export const R_PHONEME_DATA: PhonemeContent = {
  name: 'Fonema R suave',
  color: 'indigo',
  taller: [
    { title: "¡Música maestro!", instruction: "Sonido de la trompeta:", sound: "Tararí, tararí", tip: "¡Siente el flujo suave!", img: "https://static.arasaac.org/pictograms/2607/2607_300.png" },
    { title: "¡la locura de la r suave!", instruction: "Si alguiene está loco, decimos que está...:", sound: "Tururú", tip: "¡No dejes que la lengua se tense!", img: "https://static.arasaac.org/pictograms/8618/8618_300.png" },
    

  ],
  semaforoPares: [
    { w1: "MORA", s1: "R suave", i1_img: "https://static.arasaac.org/pictograms/8360/8360_300.png", w2: "MOLA", s2: "Con L", i2_img: "https://static.arasaac.org/pictograms/11599/11599_300.png", target: 1 },
    { w1: "CARA", s1: "R suave", i1_img: "https://static.arasaac.org/pictograms/2684/2684_nocolor_500.png", w2: "CALA", s2: "Con L", i2_img: "https://static.arasaac.org/pictograms/25894/25894_300.png", target: 1 },
    { w1: "CORO", s1: "R suave", i1_img: "https://static.arasaac.org/pictograms/2717/2717_300.png", w2: "CODO", s2: "Con D", i2_img: "https://static.arasaac.org/pictograms/2707/2707_300.png", target: 1 },
    { w1: "PERA", s1: "R suave", i1_img: "https://static.arasaac.org/pictograms/2561/2561_300.png", w2: "PENA", s2: "Con N", i2_img: "https://static.arasaac.org/pictograms/31939/31939_300.png", target: 1 },
    { w1: "TORO", s1: "R suave", i1_img: "https://static.arasaac.org/pictograms/2595/2595_300.png", w2: "TODO", s2: "Con D", i2_img: "https://static.arasaac.org/pictograms/27091/27091_300.png", target: 1 },
    { w1: "MURO", s1: "R suave", i1_img: "https://static.arasaac.org/pictograms/8266/8266_300.png", w2: "MUDO", s2: "Con D", i2_img: "https://static.arasaac.org/pictograms/4702/4702_300.png", target: 1 },
    { w1: "OREJA", s1: "R suave", i1_img: "https://static.arasaac.org/pictograms/2871/2871_300.png", w2: "OVEJA", s2: "Con V", i2_img: "https://static.arasaac.org/pictograms/2489/2489_300.png", target: 1 },
    { w1: "MIRA", s1: "R suave", i1_img: "https://static.arasaac.org/pictograms/2474/2474_300.png", w2: "MINA", s2: "Con N", i2_img: "https://static.arasaac.org/pictograms/8630/8630_300.png", target: 1 },
    { w1: "CURA", s1: "R suave", i1_img: "https://static.arasaac.org/pictograms/30700/30700_300.png", w2: "CUNA", s2: "Con N", i2_img: "https://static.arasaac.org/pictograms/5980/5980_300.png", target: 1 },
    { w1: "CARO", s1: "R suave", i1_img: "https://static.arasaac.org/pictograms/4589/4589_300.png", w2: "CARRO", s2: "R fuerte", i2_img: "https://static.arasaac.org/pictograms/21506/21506_300.png", target: 1 }
  ],
  semaforoRadar: [
    { word: "Paraguas", img: "https://static.arasaac.org/pictograms/2500/2500_300.png", hasTarget: true },
    { word: "Salero", img: "https://static.arasaac.org/pictograms/2554/2554_300.png", hasTarget: true },
    { word: "Caballero", img: "https://static.arasaac.org/pictograms/5406/5406_300.png", hasTarget: true },
    { word: "Biberón", img: "https://static.arasaac.org/pictograms/4577/4577_300.png", hasTarget: true },
    { word: "Pirámide", img: "https://static.arasaac.org/pictograms/8190/8190_300.png", hasTarget: true },
    { word: "Caracol", img: "https://static.arasaac.org/pictograms/8061/8061_300.png", hasTarget: true },
    { word: "Canguro", img: "https://static.arasaac.org/pictograms/2313/2313_300.png", hasTarget: true },
    { word: "Jirafa", img: "https://static.arasaac.org/pictograms/2437/2437_300.png", hasTarget: true },
    { word: "Tiburón", img: "https://static.arasaac.org/pictograms/2589/2589_300.png", hasTarget: true },
    { word: "Febrero", img: "https://static.arasaac.org/pictograms/6498/6498_300.png", hasTarget: true },
    { word: "Araña", img: "https://static.arasaac.org/pictograms/38275/38275_300.png", hasTarget: true },
    { word: "Verano", img: "https://static.arasaac.org/pictograms/5604/5604_300.png", hasTarget: true },
    { word: "Pintura", img: "https://static.arasaac.org/pictograms/4870/4870_300.png", hasTarget: true },
    { word: "Enero", img: "https://static.arasaac.org/pictograms/6488/6488_300.png", hasTarget: true },
    { word: "Espirales", img: "https://static.arasaac.org/pictograms/37733/37733_300.png", hasTarget: true },
    { word: "Primavera", img: "https://static.arasaac.org/pictograms/5553/5553_300.png", hasTarget: true },
    { word: "Mar", img: "https://static.arasaac.org/pictograms/2925/2925_300.png", hasTarget: true },
    { word: "Collar", img: "https://static.arasaac.org/pictograms/2347/2347_300.png", hasTarget: true },
    { word: "Cartera", img: "https://static.arasaac.org/pictograms/2688/2688_300.png", hasTarget: true },
    { word: "Árbol", img: "https://static.arasaac.org/pictograms/3057/3057_300.png", hasTarget: true },
    { word: "Bocadillo", img: "https://static.arasaac.org/pictograms/2281/2281_300.png", hasTarget: false },
    { word: "Cometa", img: "https://static.arasaac.org/pictograms/2350/2350_300.png", hasTarget: false },
    { word: "Gato", img: "https://static.arasaac.org/pictograms/7114/7114_300.png", hasTarget: false },
    { word: "Espina", img: "https://static.arasaac.org/pictograms/5459/5459_300.png", hasTarget: false },
    { word: "Espinaca", img: "https://static.arasaac.org/pictograms/8311/8311_300.png", hasTarget: false },
    { word: "Espejo", img: "https://static.arasaac.org/pictograms/8573/8573_300.png", hasTarget: false },
    { word: "Dedo", img: "https://static.arasaac.org/pictograms/3298/3298_300.png", hasTarget: false },
    { word: "Montaña", img: "https://static.arasaac.org/pictograms/2909/2909_300.png", hasTarget: false },
    { word: "Escuela", img: "https://static.arasaac.org/pictograms/3082/3082_300.png", hasTarget: false },
    { word: "Lomo", img: "https://static.arasaac.org/pictograms/26178/26178_300.png", hasTarget: false },
    { word: "Estuche", img: "https://static.arasaac.org/pictograms/8575/8575_300.png", hasTarget: false },
    { word: "Junio", img: "https://static.arasaac.org/pictograms/6539/6539_300.png", hasTarget: false },
    { word: "Sábado", img: "https://static.arasaac.org/pictograms/6605/6605_300.png", hasTarget: false }
  ],
  pistaEcoTitle: "Suena o no suena con R suave",
  pistaEco: [
    { word: "Paraguas", img: "https://static.arasaac.org/pictograms/2500/2500_300.png", hasTarget: true },
    { word: "Salero", img: "https://static.arasaac.org/pictograms/2554/2554_300.png", hasTarget: true },
    { word: "Caballero", img: "https://static.arasaac.org/pictograms/5406/5406_300.png", hasTarget: true },
    { word: "Biberón", img: "https://static.arasaac.org/pictograms/4577/4577_300.png", hasTarget: true },
    { word: "Pirámide", img: "https://static.arasaac.org/pictograms/8190/8190_300.png", hasTarget: true },
    { word: "Caracol", img: "https://static.arasaac.org/pictograms/8061/8061_300.png", hasTarget: true },
    { word: "Canguro", img: "https://static.arasaac.org/pictograms/2313/2313_300.png", hasTarget: true },
    { word: "Jirafa", img: "https://static.arasaac.org/pictograms/2437/2437_300.png", hasTarget: true },
    { word: "Tiburón", img: "https://static.arasaac.org/pictograms/2589/2589_300.png", hasTarget: true },
    { word: "Febrero", img: "https://static.arasaac.org/pictograms/6498/6498_300.png", hasTarget: true },
    { word: "Araña", img: "https://static.arasaac.org/pictograms/38275/38275_300.png", hasTarget: true },
    { word: "Verano", img: "https://static.arasaac.org/pictograms/5604/5604_300.png", hasTarget: true },
    { word: "Pintura", img: "https://static.arasaac.org/pictograms/4870/4870_300.png", hasTarget: true },
    { word: "Enero", img: "https://static.arasaac.org/pictograms/6488/6488_300.png", hasTarget: true },
    { word: "Espirales", img: "https://static.arasaac.org/pictograms/37733/37733_300.png", hasTarget: true },
    { word: "Primavera", img: "https://static.arasaac.org/pictograms/5553/5553_300.png", hasTarget: true },
    { word: "Mar", img: "https://static.arasaac.org/pictograms/2925/2925_300.png", hasTarget: true },
    { word: "Collar", img: "https://static.arasaac.org/pictograms/2347/2347_300.png", hasTarget: true },
    { word: "Cartera", img: "https://static.arasaac.org/pictograms/2688/2688_300.png", hasTarget: true },
    { word: "Árbol", img: "https://static.arasaac.org/pictograms/3057/3057_300.png", hasTarget: true },
    { word: "Bocadillo", img: "https://static.arasaac.org/pictograms/2281/2281_300.png", hasTarget: false },
    { word: "Cometa", img: "https://static.arasaac.org/pictograms/2350/2350_300.png", hasTarget: false },
    { word: "Gato", img: "https://static.arasaac.org/pictograms/7114/7114_300.png", hasTarget: false },
    { word: "Espina", img: "https://static.arasaac.org/pictograms/5459/5459_300.png", hasTarget: false },
    { word: "Espinaca", img: "https://static.arasaac.org/pictograms/8311/8311_300.png", hasTarget: false },
    { word: "Espejo", img: "https://static.arasaac.org/pictograms/8573/8573_300.png", hasTarget: false },
    { word: "Dedo", img: "https://static.arasaac.org/pictograms/3298/3298_300.png", hasTarget: false },
    { word: "Montaña", img: "https://static.arasaac.org/pictograms/2909/2909_300.png", hasTarget: false },
    { word: "Escuela", img: "https://static.arasaac.org/pictograms/3082/3082_300.png", hasTarget: false },
    { word: "Lomo", img: "https://static.arasaac.org/pictograms/26178/26178_300.png", hasTarget: false },
    { word: "Estuche", img: "https://static.arasaac.org/pictograms/8575/8575_300.png", hasTarget: false },
    { word: "Junio", img: "https://static.arasaac.org/pictograms/6539/6539_300.png", hasTarget: false },
    { word: "Sábado", img: "https://static.arasaac.org/pictograms/6605/6605_300.png", hasTarget: false }
  ],
  pistaDecir: [
    { word: "pera", img: "https://static.arasaac.org/pictograms/2561/2561_300.png", category: "contiene" },
    { word: "tijeras", img: "https://static.arasaac.org/pictograms/2591/2591_300.png", category: "contiene" },
    { word: "aro", img: "https://static.arasaac.org/pictograms/3253/3253_300.png", category: "contiene" },
    { word: "toro", img: "https://static.arasaac.org/pictograms/2595/2595_300.png", category: "contiene" },
    { word: "oruga", img: "https://static.arasaac.org/pictograms/16727/16727_300.png", category: "contiene" },
    { word: "piruleta", img: "https://static.arasaac.org/pictograms/2832/2832_300.png", category: "contiene" },
    { word: "pared", img: "https://static.arasaac.org/pictograms/2860/2860_300.png", category: "contiene" },
    { word: "sirena", img: "https://static.arasaac.org/pictograms/5589/5589_300.png", category: "contiene" },
    { word: "nariz", img: "https://static.arasaac.org/pictograms/2887/2887_nocolor_500.png", category: "contiene" },
    { word: "mariquita", img: "https://static.arasaac.org/pictograms/2924/2924_300.png", category: "contiene" },
    { word: "carta", img: "https://static.arasaac.org/pictograms/2688/2688_300.png", category:  "inversa" },
    { word: "arbol", img: "https://static.arasaac.org/pictograms/3057/3057_300.png", category: "inversa" },
    { word: "corbata", img: "https://static.arasaac.org/pictograms/4614/4614_300.png", category: "inversa" },
    { word: "tortuga", img: "https://static.arasaac.org/pictograms/26503/26503_300.png", category: "inversa" },
    { word: "curva", img: "https://static.arasaac.org/pictograms/4681/4681_300.png", category: "inversa" },
    { word: "burbuja", img: "https://static.arasaac.org/pictograms/8389/8389_300.png", category: "inversa" },
    { word: "cerdo", img: "https://static.arasaac.org/pictograms/24972/24972_300.png", category: "inversa" },
    { word: "serpiente", img: "https://static.arasaac.org/pictograms/2568/2568_300.png", category: "inversa" },
    { word: "circo", img: "https://static.arasaac.org/pictograms/6450/6450_300.png", category: "inversa" },
    { word: "círculo", img: "https://static.arasaac.org/pictograms/4603/4603_300.png", category: "inversa" },
    { word: "mar", img: "https://static.arasaac.org/pictograms/2925/2925_300.png", category: "final" },
    { word: "collar", img: "https://static.arasaac.org/pictograms/2347/2347_300.png", category: "final" },
    { word: "tambor", img: "https://static.arasaac.org/pictograms/2578/2578_300.png", category: "final" },
    { word: "tenedor", img: "https://static.arasaac.org/pictograms/2588/2588_300.png", category: "final" },
    { word: "sur", img: "https://static.arasaac.org/pictograms/8228/8228_300.png", category: "final" },
    { word: "yogur", img: "https://static.arasaac.org/pictograms/2618/2618_300.png", category: "final" },
    { word: "chofer", img: "https://static.arasaac.org/pictograms/3019/3019_300.png", category: "final" },
    { word: "sueter", img: "https://static.arasaac.org/pictograms/2436/2436_300.png", category: "final" },
    { word: "salir", img: "https://static.arasaac.org/pictograms/2806/2806_300.png", category: "final" },
    { word: "dormir", img: "https://static.arasaac.org/pictograms/2369/2369_300.png", category: "final" }
  ],
  gameImages: [
    { img: "https://static.arasaac.org/pictograms/2561/2561_300.png", name: "PERA" }, { img: "https://static.arasaac.org/pictograms/2591/2591_300.png", name: "TIJERAS" }, { img: "https://static.arasaac.org/pictograms/3253/3253_300.png", name: "ARO" }, { img: "https://static.arasaac.org/pictograms/2595/2595_300.png", name: "TORO" },
    { img: "https://static.arasaac.org/pictograms/16727/16727_300.png", name: "ORUGA" }, { img: "https://static.arasaac.org/pictograms/2832/2832_300.png", name: "PIRULETA" }, { img: "https://static.arasaac.org/pictograms/2860/2860_300.png", name: "PARED" }, { img: "https://static.arasaac.org/pictograms/5589/5589_300.png", name: "SIRENA" },
    { img: "https://static.arasaac.org/pictograms/2887/2887_300.png", name: "NARIZ" }, { img: "https://static.arasaac.org/pictograms/2924/2924_300.png", name: "MARIQUITA" }, { img: "https://static.arasaac.org/pictograms/2688/2688_300.png", name: "CARTA" }, { img: "https://static.arasaac.org/pictograms/3057/3057_300.png", name: "ÁRBOL" },
    { img: "https://static.arasaac.org/pictograms/4614/4614_300.png", name: "CORBATA" }, { img: "https://static.arasaac.org/pictograms/26503/26503_300.png", name: "TORTUGA" }, { img: "https://static.arasaac.org/pictograms/4681/4681_300.png", name: "CURVA" }, { img: "https://static.arasaac.org/pictograms/8389/8389_300.png", name: "BURBUJA" },
    { img: "https://static.arasaac.org/pictograms/24972/24972_300.png", name: "CERDO" }, { img: "https://static.arasaac.org/pictograms/2568/2568_300.png", name: "SERPIENTE" }, { img: "https://static.arasaac.org/pictograms/6450/6450_300.png", name: "CIRCO" }, { img: "https://static.arasaac.org/pictograms/4603/4603_300.png", name: "CÍRCULO" }
  ],
  pistaFrases: [
    "En el campo hay gusanos,mariquitas, orugas, mariposas y hormigas.",
    "El pirata tiene un tesoro de diamantes escondido en la arena.",
    "En la tienda de golosinas hay muchos caramelos de colores.",
    "Los de mora son los que más me gustan.",
    "El pastelero ha hecho una tarta con mermelada de pera.Está en el horno",
    "Coral no tiene dinero en su monedero.",
    "Ricardo tiene una careta de superhéroe.",
    "La sirena es amiga del marinero.",
    "El periódico está en la papelera.",
    "El arco de Mario es dorado",
    "Marta perdió el arpa de Puri" ,
    "Mi hermano colorea la pera" ,
    "El caracol se esconde en su caparazón",
    "No quiero ir al parque",
  ],
  pistaTrabalenguas: [
    "El amor es una locura que solo el cura lo cura, pero el cura que lo cura comete una gran locura.",
    "El cloro no aclara la cara del loro con aro de oro pero el cloro aclara el aro de oro en la cara del loro",
    "Si el caracol tuviera cara como tiene el caracol, fuera cara fuera col fuera caracol con cara"
  ],
  pistaCompletar: [
    { phrase: "En la cabeza tenemos el pelo y la ... ", word: "CARA" },
    { phrase: "Las medicinas se compran en la ...", word: "FARMACIA" },
    { phrase: "Los bebés beben la leche en el ....", word: "BIBERÓN" },
    { phrase: "Cuando llueve nos protegemos de la lluvia con un ...", word: "PARAGUAS" },
    { phrase: "Después del lunes va el...", word: "MARTES" },
    { phrase: "Por el mar pueden navegar los...", word: "BARCOS" },
    { phrase: "Los tres Reyes Magos llevaban mirra, incienso y ...", word: "ORO" },
    { phrase: "En el reloj miramos la...", word: "HORA" },
    { phrase: "Para que no se nos caigan los pantalones nos ponemos el...", word: "CINTURÓN" },

  ]
};
