import { PhonemeContent } from '../types';

export const R_PHONEME_DATA: PhonemeContent = {
  name: 'Fonema R suave',
  color: 'indigo',
  taller: [
    { title: "¡Música maestro!", instruction: "Sonido de la trompeta:", sound: "Tararí, tararí", tip: "¡Siente el flujo suave!", img: "trompeta" },
    { title: "¡la locura de la r suave!", instruction: "Si alguiene está loco, decimos que está...:", sound: "Tururú", tip: "¡No dejes que la lengua se tense!", img: "loco" },
    

  ],
  semaforoPares: [
    { w1: "MORA", s1: "R suave", i1_img: "MORA", w2: "MOLA", s2: "Con L", i2_img: "MOLA", target: 1 },
    { w1: "CARA", s1: "R suave", i1_img: "CARA", w2: "CALA", s2: "Con L", i2_img: "CALA", target: 1 },
    { w1: "CORO", s1: "R suave", i1_img: "CORO", w2: "CODO", s2: "Con D", i2_img: "CODO", target: 1 },
    { w1: "PERA", s1: "R suave", i1_img: "PERA", w2: "PENA", s2: "Con N", i2_img: "PENA", target: 1 },
    { w1: "TORO", s1: "R suave", i1_img: "TORO", w2: "TODO", s2: "Con D", i2_img: "TODO", target: 1 },
    { w1: "MURO", s1: "R suave", i1_img: "MURO", w2: "MUDO", s2: "Con D", i2_img: "MUDO", target: 1 },
    { w1: "OREJA", s1: "R suave", i1_img: "OREJA", w2: "OVEJA", s2: "Con V", i2_img: "OVEJA", target: 1 },
    { w1: "MIRA", s1: "R suave", i1_img: "MIRA", w2: "MINA", s2: "Con N", i2_img: "MINA", target: 1 },
    { w1: "CURA", s1: "R suave", i1_img: "CURA", w2: "CUNA", s2: "Con N", i2_img: "CUNA", target: 1 },
    { w1: "CARO", s1: "R suave", i1_img: "CARO", w2: "CARRO", s2: "R fuerte", i2_img: "CARRO", target: 1 }
  ],
  semaforoRadar: {
    title: "Suena o no suena con R suave",
    items: [
      { word: "Paraguas", img: "Paraguas", hasTarget: true },
      { word: "Salero", img: "Salero", hasTarget: true },
      { word: "Caballero", img: "Caballero", hasTarget: true },
      { word: "Biberón", img: "Biberón", hasTarget: true },
      { word: "Pirámide", img: "Pirámide", hasTarget: true },
      { word: "Caracol", img: "Caracol", hasTarget: true },
      { word: "Canguro", img: "Canguro", hasTarget: true },
      { word: "Jirafa", img: "Jirafa", hasTarget: true },
      { word: "Tiburón", img: "Tiburón", hasTarget: true },
      { word: "Febrero", img: "Febrero", hasTarget: true },
      { word: "Araña", img: "Araña", hasTarget: true },
      { word: "Verano", img: "Verano", hasTarget: true },
      { word: "Pintura", img: "Pintura", hasTarget: true },
      { word: "Enero", img: "Enero", hasTarget: true },
      { word: "Espirales", img: "Espirales", hasTarget: true },
      { word: "Primavera", img: "Primavera", hasTarget: true },
      { word: "Mar", img: "Mar", hasTarget: true },
      { word: "Collar", img: "Collar", hasTarget: true },
      { word: "Cartera", img: "Cartera", hasTarget: true },
      { word: "Árbol", img: "Árbol", hasTarget: true },
      { word: "Bocadillo", img: "Bocadillo", hasTarget: false },
      { word: "Cometa", img: "Cometa", hasTarget: false },
      { word: "Gato", img: "Gato", hasTarget: false },
      { word: "Espina", img: "Espina", hasTarget: false },
      { word: "Espinaca", img: "Espinaca", hasTarget: false },
      { word: "Espejo", img: "Espejo", hasTarget: false },
      { word: "Dedo", img: "Dedo", hasTarget: false },
      { word: "Montaña", img: "Montaña", hasTarget: false },
      { word: "Escuela", img: "Escuela", hasTarget: false },
      { word: "Lomo", img: "Lomo", hasTarget: false },
      { word: "Estuche", img: "Estuche", hasTarget: false },
      { word: "Junio", img: "Junio", hasTarget: false },
      { word: "Sábado", img: "Sábado", hasTarget: false }
    ]
  },
  pistaDecir: [
    { word: "pera", img: "pera", category: "contiene" },
    { word: "tijeras", img: "tijeras", category: "contiene" },
    { word: "aro", img: "aro", category: "contiene" },
    { word: "toro", img: "toro", category: "contiene" },
    { word: "oruga", img: "oruga", category: "contiene" },
    { word: "piruleta", img: "piruleta", category: "contiene" },
    { word: "pared", img: "pared", category: "contiene" },
    { word: "sirena", img: "sirena", category: "contiene" },
    { word: "nariz", img: "nariz", category: "contiene" },
    { word: "mariquita", img: "mariquita", category: "contiene" },
    { word: "carta", img: "carta", category:  "inversa" },
    { word: "arbol", img: "arbol", category: "inversa" },
    { word: "corbata", img: "corbata", category: "inversa" },
    { word: "tortuga", img: "tortuga", category: "inversa" },
    { word: "curva", img: "curva", category: "inversa" },
    { word: "burbuja", img: "burbuja", category: "inversa" },
    { word: "cerdo", img: "cerdo", category: "inversa" },
    { word: "serpiente", img: "serpiente", category: "inversa" },
    { word: "circo", img: "circo", category: "inversa" },
    { word: "círculo", img: "círculo", category: "inversa" },
    { word: "mar", img: "mar", category: "final" },
    { word: "collar", img: "collar", category: "final" },
    { word: "tambor", img: "tambor", category: "final" },
    { word: "tenedor", img: "tenedor", category: "final" },
    { word: "sur", img: "sur", category: "final" },
    { word: "yogur", img: "yogur", category: "final" },
    { word: "chofer", img: "chofer", category: "final" },
    { word: "sueter", img: "sueter", category: "final" },
    { word: "salir", img: "salir", category: "final" },
    { word: "dormir", img: "dormir", category: "final" }
  ],
  gameImages: [
    { img: "PERA", name: "PERA" }, { img: "TIJERAS", name: "TIJERAS" }, { img: "ARO", name: "ARO" }, { img: "TORO", name: "TORO" },
    { img: "ORUGA", name: "ORUGA" }, { img: "PIRULETA", name: "PIRULETA" }, { img: "PARED", name: "PARED" }, { img: "SIRENA", name: "SIRENA" },
    { img: "NARIZ", name: "NARIZ" }, { img: "MARIQUITA", name: "MARIQUITA" }, { img: "CARTA", name: "CARTA" }, { img: "ÁRBOL", name: "ÁRBOL" },
    { img: "CORBATA", name: "CORBATA" }, { img: "TORTUGA", name: "TORTUGA" }, { img: "CURVA", name: "CURVA" }, { img: "BURBUJA", name: "BURBUJA" },
    { img: "CERDO", name: "CERDO" }, { img: "SERPIENTE", name: "SERPIENTE" }, { img: "CIRCO", name: "CIRCO" }, { img: "CÍRCULO", name: "CÍRCULO" },
    { img: "PARAGUAS", name: "PARAGUAS" }, { img: "SALERO", name: "SALERO" }, { img: "CABALLERO", name: "CABALLERO" }, { img: "BIBERÓN", name: "BIBERÓN" },
    { img: "PIRÁMIDE", name: "PIRÁMIDE" }, { img: "CARACOL", name: "CARACOL" }, { img: "CANGURO", name: "CANGURO" }, { img: "JIRAFA", name: "JIRAFA" },
    { img: "TIBURÓN", name: "TIBURÓN" }, { img: "ARAÑA", name: "ARAÑA" }
  ],
  pistaFrases: [
    "En el campo hay gusanos,mariquitas, orugas, mariposas y hormigas.",
    "El pirata tiene un tesoro de diamantes escondido en la arena.",
    "En la tienda de golosinas hay muchos caramelos de colores.",
    "Los de mora son los que más me gustan.",
    "El pastelero ha hecho una tarta con mermelada de pera.Está en el horno",
    "Coral no tiene dinero en su monedero.",
    "Ricardo tiene una careta de superhéroe.",
    "La sirena es amiga del marinero.",
    "El periódico está en la papelera.",
    "El arco de Mario es dorado",
    "Marta perdió el arpa de Puri" ,
    "Mi hermano colorea la pera" ,
    "El caracol se esconde en su caparazón",
    "No quiero ir al parque",
  ],
  pistaTrabalenguas: [
    "El amor es una locura que solo el cura lo cura, pero el cura que lo cura comete una gran locura.",
    "El cloro no aclara la cara del loro con aro de oro pero el cloro aclara el aro de oro en la cara del loro",
    "Si el caracol tuviera cara como tiene el caracol, fuera cara fuera col fuera caracol con cara"
  ],
  pistaCompletar: [
    { phrase: "En la cabeza tenemos el pelo y la ... ", word: "CARA" },
    { phrase: "Las medicinas se compran en la ...", word: "FARMACIA" },
    { phrase: "Los bebés beben la leche en el ....", word: "BIBERÓN" },
    { phrase: "Cuando llueve nos protegemos de la lluvia con un ...", word: "PARAGUAS" },
    { phrase: "Después del lunes va el...", word: "MARTES" },
    { phrase: "Por el mar pueden navegar los...", word: "BARCOS" },
    { phrase: "Los tres Reyes Magos llevaban mirra, incienso y ...", word: "ORO" },
    { phrase: "En el reloj miramos la...", word: "HORA" },
    { phrase: "Para que no se nos caigan los pantalones nos ponemos el...", word: "CINTURÓN" },

  ],
  simulatorDescription: "Mandíbula: apertura media. Dientes: entreabiertos. Labios: entreabiertos. Lengua: el ápex lingual presiona los alveolos superiores y los bordes laterales se apoyan en la parte interna de los molares superiores. El ápice desciende permitiendo la salida de aire acumulado.",
  videoUrl: "https://www.youtube.com/watch?v=LJ7-REF1a9E",
  referenceUrl: "https://soundsofspeech.uiowa.edu/spanish/details"
};
