import { PhonemeContent } from '../types';

export const RR_PHONEME_DATA: PhonemeContent = {
  name: 'Fonema RR',
  color: 'rose',
  taller: [
    { title: "¡Vibra la R!", instruction: "Pon la lengua arriba y hazla vibrar fuerte:", sound: "RR-RR-RR", tip: "¡Imagina que haces un motorcito!", },
    { title: "¡Llaman al teléfono!", instruction: "Repite con fuerza:", sound: "RING RING", tip: "¡Siente la R larga dentro de la boca!", img: "https://static.arasaac.org/pictograms/26479/26479_300.png" },
    { title: "¡El mundial de motos!", instruction: "¿Cómo es el sonido de una moto?:", sound: "¡Bruuum, bruum", tip: "¡No tengas miedo de la R fuerte!", img: "https://static.arasaac.org/pictograms/2480/2480_300.png" }
  ],
  semaforoPares: [
    { w1: "PELO", s1: "Con L", i1_img: "", w2: "PERRO", s2: "R fuerte", i2_img: "", target: 2 },
    { w1: "GATA", s1: "Con G", i1_img: "", w2: "RATA", s2: "R fuerte", i2_img: "", target: 2 },
    { w1: "SONRIE", s1: "R fuerte", i1_img: "", w2: "SOFRÍE", s2: "Con F", i2_img: "", target: 1 },
    { w1: "RAYO", s1: "R fuerte", i1_img: "", w2: "GALLO", s2: "Con G", i2_img: "", target: 1 },
    { w1: "RAMA", s1: "R fuerte", i1_img: "", w2: "CAMA", s2: "Con G", i2_img: "", target: 1 },
    { w1: "VAGO", s1: "Con V", i1_img: "", w2: "BARRO", s2: "R fuerte", i2_img: "", target: 2 },
    { w1: "BORRA", s1: "R suave", i1_img: "", w2: "BOLA", s2: "Con B", i2_img: "", target: 1 },
    { w1: "RANA", s1: "R fuerte", i1_img: "", w2: "LANA", s2: "Con L", i2_img: "", target: 1 }
  ],
  semaforoRadar: [],
  pistaEcoTitle: "Suena o no suena con RR",
  pistaEco: [
    { word: "Burro", img: "", hasTarget: true },
    { word: "Ropa", img: "", hasTarget: false },
    { word: "Marrón", img: "", hasTarget: true },
    { word: "Blanco", img: "", hasTarget: false },
    { word: "Gorro", img: "", hasTarget: true },
    { word: "Sardina", img: "", hasTarget: false },
    { word: "Gorra", img: "", hasTarget: true },
    { word: "Guantes", img: "", hasTarget: false },
    { word: "Macarrones", img: "", hasTarget: true },
    { word: "Héroe", img: "", hasTarget: false },
    { word: "Borraja", img: "", hasTarget: true },
    { word: "Armadillo", img: "", hasTarget: false },
    { word: "Pizarra", img: "", hasTarget: true },
    { word: "Plateado", img: "", hasTarget: false },
    { word: "Arroz", img: "", hasTarget: true },
    { word: "Gnomo", img: "", hasTarget: false },
    { word: "Borrador", img: "", hasTarget: true },
    { word: "Saltamontes", img: "", hasTarget: false },
    { word: "Calcetines", img: "", hasTarget: false },
    { word: "Verde", img: "", hasTarget: false },
    { word: "Caballero", img: "", hasTarget: false },
    { word: "Rana", img: "", hasTarget: false },
    { word: "Camiseta", img: "", hasTarget: false },
    { word: "Lechuga", img: "", hasTarget: false },
    { word: "Armadura", img: "", hasTarget: false },
    { word: "Caballo", img: "", hasTarget: false },
    { word: "Espejo", img: "", hasTarget: false },
    { word: "Recreo", img: "", hasTarget: false },
    { word: "Horquilla", img: "", hasTarget: false },
    { word: "Montaña", img: "", hasTarget: false },
    { word: "Mesa", img: "", hasTarget: false },
    { word: "Rosa", img: "", hasTarget: false },
    { word: "Acelga", img: "", hasTarget: false },
    { word: "Pirata", img: "", hasTarget: false },
    { word: "Silla", img: "", hasTarget: false },
    { word: "Azul", img: "", hasTarget: false },
    { word: "Canelones", img: "", hasTarget: false },
    { word: "Pato", img: "", hasTarget: false },
    { word: "Tiza", img: "", hasTarget: false },
    { word: "Armario", img: "", hasTarget: false },
  ],
  pistaDecir: [
    { word: "Rana", img: "🐶", category: "inicio" },
    { word: "Radio", img: "🚗", category: "inicio" },
    { word: "Rosa", img: "🍚", category: "inicio" },
    { word: "Rojo", img: "🧢", category: "inicio" },
    { word: "Ruso", img: "🐴", category: "inicio" },
    { word: "Rueda", img: "🧱", category: "inicio" },
    { word: "Rey", img: "🌍", category: "inicio" },
    { word: "Reloj", img: "⛰️", category: "inicio" },
    { word: "Río", img: "🦊", category: "inicio" },
    { word: "Risa", img: "🛒", category: "inicio" },
    { word: "Jarra", img: "🏃", category: "contiene" },
    { word: "Tierra", img: "🐄", category: "contiene" },
    { word: "Gorro", img: "🛠️", category: "contiene" },
    { word: "Perro", img: "📦", category: "contiene" },
    { word: "Serrucho", img: "⚡", category: "contiene" },
    { word: "Verruga", img: "🛣️", category: "contiene" },
    { word: "Torre", img: "🔥", category: "contiene" },
    { word: "Guerrero", img: "🛢️", category: "contiene" },
    { word: "Carrito", img: "🎸", category: "contiene" },
    { word: "Barril", img: "🎶", category: "contiene" },
    { word: "Raqueta", img: "🦊", category: "inicio" },
    { word: "Guitarra", img: "🐴", category: "contiene" },
    { word: "Churro", img: "🧱", category: "contiene" },
    { word: "Rubio", img: "🚗", category: "inicio" },
    { word: "Arruga", img: "⛰️", category: "contiene" },
    { word: "Reina", img: "🏃", category: "inicio" },
    { word: "Carretera", img: "📦", category: "contiene" },
    { word: "Rizado", img: "🏃", category: "inicio" },
    { word: "Cigarrillo", img: "🚓", category: "contiene" }
  ],
  gameImages: [
    { img: "🐶", name: "PERRO" }, { img: "🚗", name: "CARRO" }, { img: "🍚", name: "ARROZ" }, { img: "🧢", name: "GORRA" },
    { img: "🐴", name: "BURRO" }, { img: "🧱", name: "BARRO" }, { img: "🏃", name: "CORRER" }, { img: "🌍", name: "TIERRA" },
    { img: "⛰️", name: "CERRO" }, { img: "🦊", name: "ZORRA" }, { img: "🛣️", name: "CARRETERA" }, { img: "🛢️", name: "BARRIL" },
    { img: "🛒", name: "CARRETA" }, { img: "🎸", name: "ARREGLAR" }, { img: "🔧", name: "ARREGLO" }, { img: "🎵", name: "ARRORRÓ" },
    { img: "🌊", name: "ARROYO" }, { img: "🥖", name: "BARRA" }, { img: "🌿", name: "TIERRA" }, { img: "🔥", name: "ARREBATO" }
  ],
  pistaFrases: [
    "La rana Renata roe pan.", 
    "Felipe mueve el remo en el río.",
    "Ramón sierra el árbol.",
    "Rita tiende el vestido rosa.",
    "La vaca se fue del rebaño.",
    "El arroz tiene puerros.",
    "La bota de Raúl tiene barro.",
    "El perro Curro pisa el rabo de la rata.",
    "La barrera se abrió con fuerza.",
    "El arreglo quedó muy bien hecho."
  ],
  pistaTrabalenguas: [
    "Erre con erre, guitarra, erre con erre, carro, rápido ruedan las ruedas del ferrocarril.",
    "En el carro de mi perro hay barro y arroz.",
    "El burro corre por la tierra roja."
  ],
  pistaCompletar: [
    { phrase: "El animal que tira del carro es el", word: "BURRO" },
    { phrase: "Para seguir la calle uso la", word: "CARRETERA" },
    { phrase: "En la cocina se come arroz y", word: "CARNE" },
    { phrase: "El niño va rápido porque quiere", word: "CORRER" },
    { phrase: "La barra se usa para sujetar la", word: "PUERTA" },
    { phrase: "El perro ladra y la", word: "GORRA" },
    { phrase: "El corredor cruza la", word: "META" },
    { phrase: "La tierra está cubierta de", word: "HIERBA" },
    { phrase: "El arreglo de la bici lo hizo el", word: "MECÁNICO" },
    { phrase: "El burro está en el", word: "CAMPO" }
  ]
};
