import { PhonemeContent } from '../types';

export const RR_PHONEME_DATA: PhonemeContent = {
  name: 'Fonema RR',
  color: 'rose',
  taller: [
    { title: "¡Vibra la R!", instruction: "Pon la lengua arriba y hazla vibrar fuerte:", sound: "RR-RR-RR", tip: "¡Imagina que haces un motorcito!", img: "motor" },
    { title: "¡Llaman al teléfono!", instruction: "Repite con fuerza:", sound: "RING RING", tip: "¡Siente la R larga dentro de la boca!", img: "teléfono" },
    { title: "¡El mundial de motos!", instruction: "¿Cómo es el sonido de una moto?:", sound: "¡Bruuum, bruum", tip: "¡No tengas miedo de la R fuerte!", img: "moto" }
  ],
  semaforoPares: [
    { w1: "PELO", s1: "Con L", i1_img: "PELO", w2: "PERRO", s2: "R fuerte", i2_img: "PERRO", target: 2 },
    { w1: "GATA", s1: "Con G", i1_img: "GATA", w2: "RATA", s2: "R fuerte", i2_img: "RATA", target: 2 },
    { w1: "SONRIE", s1: "R fuerte", i1_img: "SONRIE", w2: "SOFRÍE", s2: "Con F", i2_img: "SOFRÍE", target: 1 },
    { w1: "RAYO", s1: "R fuerte", i1_img: "RAYO", w2: "GALLO", s2: "Con G", i2_img: "GALLO", target: 1 },
    { w1: "RAMA", s1: "R fuerte", i1_img: "RAMA", w2: "CAMA", s2: "Con G", i2_img: "CAMA", target: 1 },
    { w1: "VAGO", s1: "Con V", i1_img: "VAGO", w2: "BARRO", s2: "R fuerte", i2_img: "BARRO", target: 2 },
    { w1: "BORRA", s1: "R suave", i1_img: "BORRAR", w2: "BOLA", s2: "Con B", i2_img: "BOLA", target: 1 },
    { w1: "RANA", s1: "R fuerte", i1_img: "RANA", w2: "LANA", s2: "Con L", i2_img: "LANA", target: 1 }
  ],
  semaforoRadar: {
    title: "Suena o no suena con RR",
    items: [
      { word: "Burro", img: "Burro", hasTarget: true },
      { word: "Ropa", img: "Ropa", hasTarget: true },
      { word: "Marrón", img: "Marrón", hasTarget: true },
      { word: "Blanco", img: "Blanco", hasTarget: false },
      { word: "Gorro", img: "Gorro", hasTarget: true },
      { word: "Sardina", img: "Sardina", hasTarget: false },
      { word: "Gorra", img: "Gorra", hasTarget: true },
      { word: "Guantes", img: "Guantes", hasTarget: false },
      { word: "Macarrones", img: "Macarrones", hasTarget: true },
      { word: "Héroe", img: "Héroe", hasTarget: false },
      { word: "Borraja", img: "Borraja", hasTarget: true },
      { word: "Armadillo", img: "Armadillo", hasTarget: false },
      { word: "Pizarra", img: "Pizarra", hasTarget: true },
      { word: "Plateado", img: "Plateado", hasTarget: false },
      { word: "Arroz", img: "Arroz", hasTarget: true },
      { word: "Gnomo", img: "Gnomo", hasTarget: false },
      { word: "Borrador", img: "Borrador", hasTarget: true },
      { word: "Saltamontes", img: "Saltamontes", hasTarget: false },
      { word: "Calcetines", img: "Calcetines", hasTarget: false },
      { word: "Verde", img: "Verde", hasTarget: false },
      { word: "Caballero", img: "Caballero", hasTarget: false },
      { word: "Rana", img: "Rana", hasTarget: true },
      { word: "Camiseta", img: "Camiseta", hasTarget: false },
      { word: "Lechuga", img: "Lechuga", hasTarget: false },
      { word: "Armadura", img: "Armadura", hasTarget: false },
      { word: "Caballo", img: "Caballo", hasTarget: false },
      { word: "Espejo", img: "Espejo", hasTarget: false },
      { word: "Recreo", img: "Recreo", hasTarget: true },
      { word: "Horquilla", img: "Horquilla", hasTarget: false },
      { word: "Montaña", img: "Montaña", hasTarget: false },
      { word: "Mesa", img: "Mesa", hasTarget: false },
      { word: "Rosa", img: "Rosa", hasTarget: true },
      { word: "Acelga", img: "Acelga", hasTarget: false },
      { word: "Pirata", img: "Pirata", hasTarget: false },
      { word: "Silla", img: "Silla", hasTarget: false },
      { word: "Azul", img: "Azul", hasTarget: false },
      { word: "Canelones", img: "Canelones", hasTarget: false },
      { word: "Pato", img: "Pato", hasTarget: false },
      { word: "Tiza", img: "Tiza", hasTarget: false },
      { word: "Armario", img: "Armario", hasTarget: false }
    ]
  },
  pistaDecir: [
    { word: "Rana", img: "Rana", category: "inicio" },
    { word: "Radio", img: "Radio", category: "inicio" },
    { word: "Rosa", img: "Rosa", category: "inicio" },
    { word: "Rojo", img: "Rojo", category: "inicio" },
    { word: "Ruso", img: "Ruso", category: "inicio" },
    { word: "Rueda", img: "Rueda", category: "inicio" },
    { word: "Rey", img: "Rey", category: "inicio" },
    { word: "Reloj", img: "Reloj", category: "inicio" },
    { word: "Río", img: "Río", category: "inicio" },
    { word: "Risa", img: "Risa", category: "inicio" },
    { word: "Jarra", img: "Jarra", category: "contiene" },
    { word: "Tierra", img: "Tierra", category: "contiene" },
    { word: "Gorro", img: "Gorro", category: "contiene" },
    { word: "Perro", img: "Perro", category: "contiene" },
    { word: "Serrucho", img: "Serrucho", category: "contiene" },
    { word: "Torre", img: "Torre", category: "contiene" },
    { word: "Guerrero", img: "Guerrero", category: "contiene" },
    { word: "Carrito", img: "Carrito", category: "contiene" },
    { word: "Barril", img: "Barril", category: "contiene" },
    { word: "Raqueta", img: "Raqueta", category: "inicio" },
    { word: "Guitarra", img: "Guitarra", category: "contiene" },
    { word: "Churro", img: "Churro", category: "contiene" },
    { word: "Rubio", img: "Rubio", category: "inicio" },
    { word: "Reina", img: "Reina", category: "inicio" },
    { word: "Carretera", img: "Carretera", category: "contiene" },
    { word: "Rizado", img: "Rizado", category: "inicio" },
    { word: "Cigarrillo", img: "Cigarrillo", category: "contiene" }
  ],
  gameImages: [
    { img: "PERRO", name: "PERRO" }, { img: "CARRO", name: "CARRO" }, { img: "ARROZ", name: "ARROZ" }, { img: "GORRA", name: "GORRA" },
    { img: "BURRO", name: "BURRO" }, { img: "BARRO", name: "BARRO" }, { img: "CORRER", name: "CORRER" }, { img: "CORRO", name: "CORRO" },
    { img: "BECERRO", name: "BECERRO" }, { img: "ZORRA", name: "ZORRA" }, { img: "CARRETERA", name: "CARRETERA" }, { img: "BARRIL", name: "BARRIL" },
    { img: "CARRETA", name: "CARRETA" }, { img: "ARREGLAR", name: "ARREGLAR" }, { img: "JARRÓN", name: "JARRÓN" }, { img: "CATARRO", name: "CATARRO" },
    { img: "ARROYO", name: "ARROYO" }, { img: "BARRA", name: "BARRA" }, { img: "TIERRA", name: "TIERRA" }, { img: "RULETA", name: "RULETA" },
    { img: "RANA", name: "RANA" }, { img: "RADIO", name: "RADIO" }, { img: "ROSA", name: "ROSA" }, { img: "REY", name: "REY" },
    { img: "RELOJ", name: "RELOJ" }, { img: "RÍO", name: "RÍO" }, { img: "RISA", name: "RISA" }, { img: "JARRA", name: "JARRA" },
    { img: "GORRO", name: "GORRO" }, { img: "SERRUCHO", name: "SERRUCHO" }
  ],
  pistaFrases: [
    "La rana Renata roe pan.",
    "Felipe mueve el remo en el río.",
    "Ramón sierra el árbol.",
    "Rita tiende el vestido rosa.",
    "La vaca se fue del rebaño.",
    "El arroz tiene puerros.",
    "La bota de Raúl tiene barro.",
    "El perro Curro pisa el rabo de la rata.",
    "La barrera se abrió con fuerza.",
    "El arreglo quedó muy bien hecho.",
    "El perro corre muy rápido por el parque.",
    "Pepe borra los dibujos con el borrador.",
  ],
  pistaTrabalenguas: [
    "Un burro comía berros y un perro se los robó, el burro lanzó un rebuzno y el perro al barro cayó.",
    "El perrito de Rita me irrita. Dile a Rita que cambie el perrito por una perrita.",
    "Rasputín era un ratón que rascaba en una risca con un tosco rasca risca rascador, rasca que rasca acabó con el risco, rasca la risca rascó un rincón.",
  ],
  pistaCompletar: [
    { phrase: "El trineo de Papá Noel es conducido por ...", word: "RENOS" },
    { phrase: "El tomate es de color rojo.", word: "ROJO" },
    { phrase: "El coche tiene cuatro...", word: "RUEDAS" },
    { phrase: "Lo contrario de pobre es...", word: "RICO" },
    { phrase: "La hora se mira en el ...", word: "RELOJ" },
    { phrase: "Para pintar lineas rectas necesitamos una ", word: "REGLA" },
    { phrase: "Lo contrario de llorar es ...", word: "REÍR" },
    { phrase: "Un animal pequeño al que le gusta mucho el queso es el...", word: "RATÓN" },
    { phrase: "Al tenis se juega con una pelota y una...", word: "RAQUETA" }
  ],
  simulatorDescription: "Mandíbula: apertura media. Dientes: entreabiertos. Labios: entreabiertos. Lengua: el ápex lingual presiona los alveolos superiores y los bordes laterales se apoyan en la parte interna de los molares superiores. El ápice lingual desciende repetidas veces permitiendo la salida de aire acumulado (vibración).",
  videoUrl: "https://www.youtube.com/watch?v=P_AQZl1A1hU",
  referenceUrl: "https://soundsofspeech.uiowa.edu/spanish/details"
};
