import { PhonemeContent } from '../types';

export const Z_PHONEME_DATA: PhonemeContent = {
  name: 'Fonema Z/C',
  color: 'emerald',
  taller: [
    { title: "¡Cazamariposas!", instruction: "Onomatopeya de golpe", sound: "¡ZAS!", tip: "¡Muerde la punta suavemente!", img: "golpe" },
    { title: "¡El Abejorro!", instruction: "Haz que vibre el aire entre los dientes:", sound: "ZZZ-ZZZ", tip: "¡Sopla flojito!", img: "abejorro" },
    { title: "¡Zumbido final!", instruction: "Di las sílabas mágicas:", sound: "ZA-CE-CI-ZO-ZU", tip: "¡No escondas la lengua!", img: "zumbido" }
  ],
  semaforoPares: [
    { w1: "ABRAZO", s1: "Con Z", i1_img: "https://static.arasaac.org/pictograms/4550/4550_300.png", w2: "ABRASO", s2: "Con S", i2_img: "https://static.arasaac.org/pictograms/6196/6196_300.png", target: 1 },
    { w1: "CAZA", s1: "Con Z", i1_img: "https://static.arasaac.org/pictograms/8533/8533_300.png", w2: "CASA", s2: "Con S", i2_img: "https://static.arasaac.org/pictograms/2317/2317_300.png", target: 1 },
    { w1: "COCER", s1: "Con C", i1_img: "https://static.arasaac.org/pictograms/6984/6984_300.png", w2: "COSER", s2: "Con S", i2_img: "https://static.arasaac.org/pictograms/2722/2722_300.png", target: 1 },
    { w1: "CAZO", s1: "Con Z", i1_img: "https://static.arasaac.org/pictograms/3230/3230_300.png", w2: "CASO", s2: "Con S", i2_img: "https://static.arasaac.org/pictograms/6965/6965_300.png", target: 1 },
    { w1: "CENA", s1: "Con C", i1_img: "https://static.arasaac.org/pictograms/4592/4592_300.png", w2: "PENA", s2: "Con P", i2_img: "https://static.arasaac.org/pictograms/31939/31939_300.png", target: 1 },
    { w1: "ZORRO", s1: "Con Z/C", i1_img: "https://static.arasaac.org/pictograms/2623/2623_300.png", w2: "CORRO", s2: "Con C", i2_img: "https://static.arasaac.org/pictograms/16739/16739_300.png", target: 1 },
    { w1: "MAZO", s1: "Con Z", i1_img: "https://static.arasaac.org/pictograms/36937/36937_300.png", w2: "MANO", s2: "Con S", i2_img: "https://static.arasaac.org/pictograms/2928/2928_300.png", target: 1 },
    { w1: "COZ", s1: "Con Z", i1_img: "https://static.arasaac.org/pictograms/16617/16617_300.png", w2: "COL", s2: "Con S", i2_img: "https://static.arasaac.org/pictograms/2708/2708_300.png", target: 1 },
    

  ],
  semaforoRadar: {
    title: "Suena o no suena con Z",
    items: [
      { word: "Abrazo", img: "Abrazo", hasTarget: true },
      { word: "Azul", img: "Azul", hasTarget: true },
      { word: "Brazo", img: "Brazo", hasTarget: true },
      { word: "Cabeza", img: "Cabeza", hasTarget: true },
      { word: "Cazo", img: "Cazo", hasTarget: true },
      { word: "Cena", img: "Cena", hasTarget: true },
      { word: "Celo", img: "Celo", hasTarget: true },
      { word: "Cereza", img: "Cereza", hasTarget: true },
      { word: "Cigüeña", img: "Cigüeña", hasTarget: true },
      { word: "Ciruela", img: "Ciruela", hasTarget: true },
      { word: "Cazar", img: "Cazar", hasTarget: true },
      { word: "Hacer", img: "Hacer", hasTarget: true },
      { word: "Lazo", img: "Lazo", hasTarget: true },
      { word: "Zapato", img: "Zapato", hasTarget: true },
      { word: "Zapatería", img: "Zapatería", hasTarget: true },
      { word: "Zorro", img: "Zorro", hasTarget: true },
      { word: "Zoo", img: "Zoo", hasTarget: true },
      { word: "Asar", img: "Asar", hasTarget: false },
      { word: "Atún", img: "Atún", hasTarget: false },
      { word: "Besar", img: "Besar", hasTarget: false },
      { word: "Beso", img: "Beso", hasTarget: false },
      { word: "Casar", img: "Casar", hasTarget: false },
      { word: "Coser", img: "Coser", hasTarget: false },
      { word: "Dado", img: "Dado", hasTarget: false },
      { word: "Dedo", img: "Dedo", hasTarget: false },
      { word: "Juego", img: "Juego", hasTarget: false },
      { word: "Jugar", img: "Jugar", hasTarget: false },
      { word: "Saco", img: "Saco", hasTarget: false },
      { word: "Sal", img: "Sal", hasTarget: false },
      { word: "Secador", img: "Secador", hasTarget: false },
      { word: "Sed", img: "Sed", hasTarget: false },
      { word: "Sol", img: "Sol", hasTarget: false }
    ]
  },
  pistaDecir: [
    { word: "zapatos", img: "zapatos", category: "inicio" },
    { word: "zoo", img: "zoo", category: "inicio" },
    { word: "zanahoria", img: "zanahoria", category: "inicio" },
    { word: "zumo", img: "zumo", category: "inicio" },
    { word: "zorro", img: "zorro", category: "inicio" },
    { word: "zueco", img: "zueco", category: "inicio" },
    { word: "cena", img: "cena", category: "inicio" },
    { word: "cebolla", img: "cebolla", category: "inicio" },
    { word: "cine", img: "cine", category: "inicio" },
    { word: "cigarro", img: "cigarro", category: "inicio" },
    { word: "taza", img: "taza", category: "contiene" },
    { word: "manzana", img: "manzana", category: "contiene" },
    { word: "pozo", img: "pozo", category: "contiene" },
    { word: "lazo", img: "lazo", category: "contiene" },
    { word: "calcetines", img: "calcetines", category: "contiene" },
    { word: "bicicleta", img: "bicicleta", category: "contiene" },
    { word: "medicina", img: "medicina", category: "contiene" },
    { word: "azul", img: "azul", category: "contiene" },
    { word: "azúcar", img: "azúcar", category: "contiene" },
    { word: "paz", img: "paz", category: "final" },
    { word: "antifaz", img: "antifaz", category: "final" },
    { word: "voz", img: "voz", category: "final" },
    { word: "luz", img: "luz", category: "final" },
    { word: "arroz", img: "arroz", category: "final" },
    { word: "cruz", img: "cruz", category: "final" },
    { word: "pez", img: "pez", category: "final" },
    { word: "nuez", img: "nuez", category: "final" },
    { word: "nariz", img: "nariz", category: "final" },
    { word: "lápiz", img: "lápiz", category: "final" }
  ],
  gameImages: [
    { img: "ZAPATO", name: "ZAPATO" }, { img: "ZORRO", name: "ZORRO" }, { img: "TAZA", name: "TAZA" }, { img: "MANZANA", name: "MANZANA" },
    { img: "ZANAHORIA", name: "ZANAHORIA" }, { img: "ZUMO", name: "ZUMO" }, { img: "CEBRA", name: "CEBRA" }, { img: "CIELO", name: "CIELO" },
    { img: "CORAZÓN", name: "CORAZÓN" }, { img: "LAZO", name: "LAZO" }, { img: "PEZ", name: "PEZ" }, { img: "LÁPIZ", name: "LÁPIZ" },
    { img: "CEREZA", name: "CEREZA" }, { img: "CEBOLLA", name: "CEBOLLA" }, { img: "CAZO", name: "CAZO" }, { img: "MAÍZ", name: "MAÍZ" },
    { img: "NARIZ", name: "NARIZ" }, { img: "CINE", name: "CINE" }, { img: "COCINA", name: "COCINA" }, { img: "AZÚCAR", name: "AZÚCAR" },
    { img: "CESTA", name: "CESTA" }, { img: "ZAPATERÍA", name: "ZAPATERÍA" }, { img: "ARROZ", name: "ARROZ" }, { img: "AZUL", name: "AZUL" },
    { img: "ZOO", name: "ZOO" }, { img: "MAZA", name: "MAZA" }, { img: "CEPILLO", name: "CEPILLO" }, { img: "CERILLA", name: "CERILLA" }
  ],
  pistaFrases: [
    "Celia cepilla a su perro.",
    "El zorro pasea por el bosque.",
    "El zorro corre por la pradera.",
    "El pozo no tiene agua.",
    "Hoy hace frío. ¡Ponte la cazadora!",
    "Merendamos un zumo y aceitunas.",
    "Los abuelos de Zoe tienen una pecera con muchos peces.",
    "En la frutería compramos cerezas y manzanas.",
    "Vimos los payasos en el circo.",
    "La ensalada tiene lechuga, tomate y cebolla.",
    "Hoy desayuné leche y cereales.",
    "Mi abuela me regaló unas zapatillas de color azul.",
    "En el zoo vimos un zorro y una cebra.",
    "Lucía lleva un lazo en el pelo.",
    "En el estanque hay un cisne.",
    "En la lavadora hay calcetines y braguitas.",
    "En la granja hay cerdos y vacas.",
    "En mi edificio hay un ascensor",
    "Recogimos las cebollas en una cesta",
    "En el recreo jugamos al baloncesto",
    "Zulema cocina acelgas y zanahorias",
    "César es cocinero y trabaja en un restaurante.",

  ],
  pistaTrabalenguas: [
    "Zipizape zapatero,zapatero remendón, ponme un lazo en mis zapatos.En mis zuecos ponme dos",
    "Un zorro muy astuto se hizo amigo de un zorrino.Le regaló un perfume con un fuerte aroma a pino",
    "El circo cierra cuando la luz se apaga en el corazón del zepelín."
  ],
  pistaCompletar: [
    { phrase: "En los pies nos ponemos los.. ", word: "ZAPATOS" },
    { phrase: "Un animal que es de rayas blancas y negras es la...", word: "CEBRA" },
    { phrase: "Una verdura que cuando la cortamos nos hace llorar es la...", word: "CEBOLLA" },
    { phrase: "Un lugar donde podemos ver muchos tipos de animales es el...", word: "ZOO" },
    { phrase: "Después del número cuatro va el número ...", word: "CINCO" },
    { phrase: "Para lavarnos los dientes utilizamos un...", word: "CEPILLO" },
    { phrase: "Los ratones comen queso y los conejos...", word: "ZANAHORIAS" },
    { phrase: "Cuadrado, rectángulo, triángulo y lo redondo se llama...", word: "CÍRCULO" },
    { phrase: "Las personas que no pueden ver están", word: "CIEGAS" },
    { phrase: "Cuando vamos a la piscina, después de bañarnos nos tumbamos en el...", word: "CÉSPED" },
  ],
  simulatorDescription: "Mandíbula: apertura media. Dientes: separados levemente. Labios: entreabiertos. Lengua: el ápice lingual se coloca entre los incisivos superiores e inferiores, presionando con mayor fuerza los superiores, aunque dejando pasar el aire entre la lengua y los incisivos superiores.",
  videoUrl: "https://www.youtube.com/watch?v=N1wt62pABpM",
  referenceUrl: "https://soundsofspeech.uiowa.edu/spanish/details"
};
