import { PhonemeContent } from '../types';

export const Z_PHONEME_DATA: PhonemeContent = {
  name: 'Fonema Z/C',
  color: 'emerald',
  taller: [
    { title: "¡Cazamariposas!", instruction: "Onomatopeya de golpe", sound: "¡ZAS!", tip: "¡Muerde la punta suavemente!", img: "https://thumbs.dreamstime.com/b/illustration-hand-drawn-zas-comic-bubble-over-white-background-ready-cutting-out-colorful-style-word-isolated-342192240.jpg" },
    { title: "¡El Abejorro!", instruction: "Haz que vibre el aire entre los dientes:", sound: "ZZZ-ZZZ", tip: "¡Sopla flojito!", img: "https://static.arasaac.org/pictograms/2239/2239_300.png" },
    { title: "¡Zumbido final!", instruction: "Di las sílabas mágicas:", sound: "ZA-CE-CI-ZO-ZU", tip: "¡No escondas la lengua!", img: "" }
  ],
  semaforoPares: [
    { w1: "ABRAZO", s1: "Con Z", i1_img: "https://static.arasaac.org/pictograms/4550/4550_300.png", w2: "ABRASO", s2: "Con S", i2_img: "https://static.arasaac.org/pictograms/6196/6196_300.png", target: 1 },
    { w1: "CAZA", s1: "Con Z", i1_img: "https://static.arasaac.org/pictograms/8533/8533_300.png", w2: "CASA", s2: "Con S", i2_img: "https://static.arasaac.org/pictograms/2317/2317_300.png", target: 1 },
    { w1: "COCER", s1: "Con C", i1_img: "https://static.arasaac.org/pictograms/6984/6984_300.png", w2: "COSER", s2: "Con S", i2_img: "https://static.arasaac.org/pictograms/2722/2722_300.png", target: 1 },
    { w1: "CAZO", s1: "Con Z", i1_img: "https://static.arasaac.org/pictograms/3230/3230_300.png", w2: "CASO", s2: "Con S", i2_img: "https://static.arasaac.org/pictograms/6965/6965_300.png", target: 1 },
    { w1: "CENA", s1: "Con C", i1_img: "https://static.arasaac.org/pictograms/4592/4592_300.png", w2: "PENA", s2: "Con P", i2_img: "https://static.arasaac.org/pictograms/31939/31939_300.png", target: 1 },
    { w1: "ZORRO", s1: "Con Z/C", i1_img: "https://static.arasaac.org/pictograms/2623/2623_300.png", w2: "CORRO", s2: "Con C", i2_img: "https://static.arasaac.org/pictograms/16739/16739_300.png", target: 1 },
    { w1: "MAZO", s1: "Con Z", i1_img: "https://static.arasaac.org/pictograms/36937/36937_300.png", w2: "MANO", s2: "Con S", i2_img: "https://static.arasaac.org/pictograms/2928/2928_300.png", target: 1 },
    { w1: "COZ", s1: "Con Z", i1_img: "https://static.arasaac.org/pictograms/16617/16617_300.png", w2: "COL", s2: "Con S", i2_img: "https://static.arasaac.org/pictograms/2708/2708_300.png", target: 1 },
    

  ],
  semaforoRadar: [],
  pistaEcoTitle: "Suena o no suena con Z",
  pistaEco: [
    { word: "Abrazo", img: "https://static.arasaac.org/pictograms/4550/4550_300.png", hasTarget: true },
    { word: "Azul", img: "https://static.arasaac.org/pictograms/4869/4869_300.png", hasTarget: true },
    { word: "Brazo", img: "https://static.arasaac.org/pictograms/2669/2669_nocolor_500.png", hasTarget: true },
    { word: "Cabeza", img: "https://static.arasaac.org/pictograms/2673/2673_300.png", hasTarget: true },
    { word: "Cazo", img: "https://static.arasaac.org/pictograms/3230/3230_300.png", hasTarget: true },
    { word: "Cena", img: "https://static.arasaac.org/pictograms/4592/4592_300.png", hasTarget: true },
    { word: "Celo", img: "https://static.arasaac.org/pictograms/2325/2325_300.png", hasTarget: true },
    { word: "Cereza", img: "https://static.arasaac.org/pictograms/8303/8303_300.png", hasTarget: true },
    { word: "Cigüeña", img: "https://static.arasaac.org/pictograms/3015/3015_300.png", hasTarget: true },
    { word: "Ciruela", img: "https://static.arasaac.org/pictograms/8305/8305_300.png", hasTarget: true },
    { word: "Cazar", img: "https://static.arasaac.org/pictograms/8533/8533_300.png", hasTarget: true },
    { word: "Hacer", img: "https://static.arasaac.org/pictograms/32751/32751_300.png", hasTarget: true },
    { word: "Lazo", img: "https://static.arasaac.org/pictograms/2946/2946_300.png", hasTarget: true },
    { word: "Zapato", img: "https://static.arasaac.org/pictograms/32923/32923_300.png", hasTarget: true },
    { word: "Zapatería", img: "https://static.arasaac.org/pictograms/2776/2776_300.png", hasTarget: true },
    { word: "Zorro", img: "https://static.arasaac.org/pictograms/2623/2623_300.png", hasTarget: true },
    { word: "Zoo", img: "https://static.arasaac.org/pictograms/4773/4773_300.png", hasTarget: true },
    { word: "Asar", img: "https://static.arasaac.org/pictograms/35441/35441_300.png", hasTarget: false },
    { word: "Atún", img: "https://static.arasaac.org/pictograms/6918/6918_300.png", hasTarget: false },
    { word: "Besar", img: "https://static.arasaac.org/pictograms/34699/34699_300.png", hasTarget: false },
    { word: "Beso", img: "https://static.arasaac.org/pictograms/4576/4576_300.png", hasTarget: false },
    { word: "Casar", img: "https://static.arasaac.org/pictograms/6965/6965_300.png", hasTarget: false },
    { word: "Coser", img: "https://static.arasaac.org/pictograms/2722/2722_300.png", hasTarget: false },
    { word: "Dado", img: "https://static.arasaac.org/pictograms/2731/2731_300.png", hasTarget: false },
    { word: "Dedo", img: "https://static.arasaac.org/pictograms/3298/3298_nocolor_500.png", hasTarget: false },
    { word: "Juego", img: "https://static.arasaac.org/pictograms/36405/36405_300.png", hasTarget: false },
    { word: "Jugar", img: "https://static.arasaac.org/pictograms/23392/23392_300.png", hasTarget: false },
    { word: "Saco", img: "https://static.arasaac.org/pictograms/6210/6210_300.png", hasTarget: false },
    { word: "Sal", img: "https://static.arasaac.org/pictograms/25576/25576_300.png", hasTarget: false },
    { word: "Secador", img: "https://static.arasaac.org/pictograms/2560/2560_300.png", hasTarget: false },
    { word: "Sed", img: "https://static.arasaac.org/pictograms/7273/7273_300.png", hasTarget: false },
    { word: "Sol", img: "https://static.arasaac.org/pictograms/7252/7252_300.png", hasTarget: false }
  ],
  pistaDecir: [
    { word: "zapatos", img: "https://static.arasaac.org/pictograms/2622/2622_300.png", category: "inicio" },
    { word: "zoo", img: "https://static.arasaac.org/pictograms/4773/4773_300.png", category: "inicio" },
    { word: "zanahoria", img: "https://static.arasaac.org/pictograms/2619/2619_300.png", category: "inicio" },
    { word: "zumo", img: "https://static.arasaac.org/pictograms/11461/11461_300.png", category: "inicio" },
    { word: "zorro", img: "https://static.arasaac.org/pictograms/2623/2623_300.png", category: "inicio" },
    { word: "zueco", img: "https://static.arasaac.org/pictograms/36606/36606_300.png", category: "inicio" },
    { word: "cena", img: "https://static.arasaac.org/pictograms/4592/4592_300.png", category: "inicio" },
    { word: "cebolla", img: "https://static.arasaac.org/pictograms/2323/2323_300.png", category: "inicio" },
    { word: "cine", img: "https://static.arasaac.org/pictograms/30387/30387_300.png", category: "inicio" },
    { word: "cigarro", img: "https://static.arasaac.org/pictograms/4601/4601_300.png", category: "inicio" },
    { word: "taza", img: "https://static.arasaac.org/pictograms/2582/2582_300.png", category: "contiene" },
    { word: "manzana", img: "https://static.arasaac.org/pictograms/2462/2462_300.png", category: "contiene" },
    { word: "pozo", img: "https://static.arasaac.org/pictograms/8197/8197_300.png", category: "contiene" },
    { word: "lazo", img: "https://static.arasaac.org/pictograms/2946/2946_300.png", category: "contiene" },
    { word: "calcetines", img: "https://static.arasaac.org/pictograms/2298/2298_300.png", category: "contiene" },
    { word: "bicicleta", img: "https://static.arasaac.org/pictograms/2277/2277_300.png", category: "contiene" },
    { word: "medicina", img: "https://static.arasaac.org/pictograms/8163/8163_300.png", category: "contiene" },
    { word: "azul", img: "https://static.arasaac.org/pictograms/4869/4869_300.png", category: "contiene" },
    { word: "azúcar", img: "https://static.arasaac.org/pictograms/25560/25560_300.png", category: "contiene" },
    { word: "paz", img: "https://static.arasaac.org/pictograms/8182/8182_300.png", category: "final" },
    { word: "antifaz", img: "https://static.arasaac.org/pictograms/5904/5904_300.png", category: "final" },
    { word: "voz", img: "https://static.arasaac.org/pictograms/39687/39687_300.png", category: "final" },
    { word: "luz", img: "https://static.arasaac.org/pictograms/8619/8619_300.png", category: "final" },
    { word: "arroz", img: "https://static.arasaac.org/pictograms/25556/25556_300.png", category: "final" },
    { word: "cruz", img: "https://static.arasaac.org/pictograms/9075/9075_300.png", category: "final" },
    { word: "pez", img: "https://static.arasaac.org/pictograms/2520/2520_300.png", category: "final" },
    { word: "nuez", img: "https://static.arasaac.org/pictograms/2880/2880_300.png", category: "final" },
    { word: "nariz", img: "https://static.arasaac.org/pictograms/2887/2887_nocolor_500.png", category: "final" },
    { word: "lápiz", img: "https://static.arasaac.org/pictograms/2440/2440_300.png", category: "final" }
  ],
  gameImages: [
    { img: "https://static.arasaac.org/pictograms/32923/32923_300.png", name: "ZAPATO" }, { img: "https://static.arasaac.org/pictograms/2623/2623_300.png", name: "ZORRO" }, { img: "https://static.arasaac.org/pictograms/2582/2582_300.png", name: "TAZA" }, { img: "https://static.arasaac.org/pictograms/2462/2462_300.png", name: "MANZANA" },
    { img: "https://static.arasaac.org/pictograms/2619/2619_300.png", name: "ZANAHORIA" }, { img: "https://static.arasaac.org/pictograms/11461/11461_300.png", name: "ZUMO" }, { img: "https://static.arasaac.org/pictograms/2324/2324_300.png", name: "CEBRA" }, { img: "https://static.arasaac.org/pictograms/38270/38270_300.png", name: "CIELO" },
    { img: "https://static.arasaac.org/pictograms/4613/4613_300.png", name: "CORAZÓN" }, { img: "https://static.arasaac.org/pictograms/2946/2946_300.png", name: "LAZO" }, { img: "https://static.arasaac.org/pictograms/2520/2520_300.png", name: "PEZ" }, { img: "https://static.arasaac.org/pictograms/2440/2440_300.png", name: "LÁPIZ" },
    { img: "https://static.arasaac.org/pictograms/8303/8303_300.png", name: "CEREZA" }, { img: "https://static.arasaac.org/pictograms/2323/2323_300.png", name: "CEBOLLA" }, { img: "https://static.arasaac.org/pictograms/3230/3230_300.png", name: "CAZO" }, { img: "https://static.arasaac.org/pictograms/7150/7150_300.png", name: "MAÍZ" },
    { img: "https://static.arasaac.org/pictograms/2887/2887_nocolor_500.png", name: "NARIZ" }, { img: "https://static.arasaac.org/pictograms/30387/30387_300.png", name: "CINE" }, { img: "https://static.arasaac.org/pictograms/33070/33070_300.png", name: "COCINA" }, { img: "https://static.arasaac.org/pictograms/25560/25560_300.png", name: "AZÚCAR" },
    { img: "https://static.arasaac.org/pictograms/3012/3012_300.png", name: "CESTA" }, { img: "https://static.arasaac.org/pictograms/2776/2776_300.png", name: "ZAPATERÍA" }, { img: "https://static.arasaac.org/pictograms/25556/25556_300.png", name: "ARROZ" }, { img: "https://static.arasaac.org/pictograms/4869/4869_300.png", name: "AZUL" },
    { img: "https://static.arasaac.org/pictograms/4773/4773_300.png", name: "ZOO" }, { img: "https://static.arasaac.org/pictograms/28549/28549_300.png", name: "MAZA" }, { img: "https://static.arasaac.org/pictograms/2694/2694_300.png", name: "CEPILLO" }, { img: "🕯️", name: "CERILLA" }
  ],
  pistaFrases: [
    "Celia cepilla a su perro.",
    "El zorro pasea por el bosque.",
    "El zorro corre por la pradera.",
    "El pozo no tiene agua.",
    "Hoy hace frío. ¡Ponte la cazadora!",
    "Merendamos un zumo y aceitunas.",
    "Los abuelos de Zoe tienen una pecera con muchos peces.",
    "En la frutería compramos cerezas y manzanas.",
    "Vimos los payasos en el circo.",
    "La ensalada tiene lechuga, tomate y cebolla.",
    "Hoy desayuné leche y cereales.",
    "Mi abuela me regaló unas zapatillas de color azul.",
    "En el zoo vimos un zorro y una cebra.",
    "Lucía lleva un lazo en el pelo.",
    "En el estanque hay un cisne.",
    "En la lavadora hay calcetines y braguitas.",
    "En la granja hay cerdos y vacas.",
    "En mi edificio hay un ascensor",
    "Recogimos las cebollas en una cesta",
    "En el recreo jugamos al baloncesto",
    "Zulema cocina acelgas y zanahorias",
    "César es cocinero y trabaja en un restaurante.",

  ],
  pistaTrabalenguas: [
    "Zipizape zapatero,zapatero remendón, ponme un lazo en mis zapatos.En mis zuecos ponme dos",
    "Un zorro muy astuto se hizo amigo de un zorrino.Le regaló un perfume con un fuerte aroma a pino",
    "El circo cierra cuando la luz se apaga en el corazón del zepelín."
  ],
  pistaCompletar: [
    { phrase: "En los pies nos ponemos los.. ", word: "ZAPATOS" },
    { phrase: "Un animal que es de rayas blancas y negras es la...", word: "CEBRA" },
    { phrase: "Una verdura que cuando la cortamos nos hace llorar es la...", word: "CEBOLLA" },
    { phrase: "Un lugar donde podemos ver muchos tipos de animales es el...", word: "ZOO" },
    { phrase: "Después del número cuatro va el número ...", word: "CINCO" },
    { phrase: "Para lavarnos los dientes utilizamos un...", word: "CEPILLO" },
    { phrase: "Los ratones comen queso y los conejos...", word: "ZANAHORIAS" },
    { phrase: "Cuadrado, rectángulo, triángulo y lo redondo se llama...", word: "CÍRCULO" },
    { phrase: "Las personas que no pueden ver están", word: "CIEGAS" },
    { phrase: "Cuando vamos a la piscina, después de bañarnos nos tumbamos en el...", word: "CÉSPED" },
  ]
};
